# Generated by Django 5.2.8 on 2025-11-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pillar', models.CharField(choices=[('BROTHERHOOD', 'Brotherhood'), ('PROFESSIONALISM', 'Professionalism'), ('SERVICE', 'Service')], max_length=20)),
                ('description', models.TextField(help_text='Description shown on hover')),
                ('icon_class', models.CharField(help_text='Emoji or icon class', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order within pillar')),
            ],
            options={
                'ordering': ['pillar', 'order', 'name'],
                'unique_together': {('pillar', 'name')},
            },
        ),
        migrations.AddField(
            model_name='brotherprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, help_text='Select badges that represent your interests', related_name='brothers', to='matchmaking.badge'),
        ),
    ]
