# Generated by Django 5.2.8 on 2025-11-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_badge_brotherprofile_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='badge',
            name='icon_image',
            field=models.CharField(default='images/badges/default.png', help_text="Path to badge icon image (e.g., 'images/badges/mentorship.png')", max_length=200),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(help_text='Admin reference description'),
        ),
    ]
